"""
Django settings for learning_log project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-s!vdy6b67x0@&k+1#%6+(58idb+t4l=%0a)!tdm4^msr-(x(4#"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 允许访问的域名列表（只填域名主体，不带 https://）
ALLOWED_HOSTS = [
    'learning-log-197557-5-1320540975.sh.run.tcloudbase.com',
    'learning-log-qinzheng123-8guhm42j495d526f-1320540975.ap-shanghai.run.wxcloudrun.com',
    os.getenv('ALLOWED_HOST', '')  # 兼容环境变量（可选）
]

# CSRF 可信源列表（需带完整 https:// 协议）
CSRF_TRUSTED_ORIGINS = [
    "https://learning-log-197557-5-1320540975.sh.run.tcloudbase.com",
    "https://learning-log-qinzheng123-8guhm42j495d526f-1320540975.ap-shanghai.run.wxcloudrun.com",
]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Application definition

INSTALLED_APPS = [
    #项目中包含的所有应用程序

    #我的应用程序
    "learning_logs",
    "users",

    # 第三方应用程序
    "bootstrap4",

    #默认添加的应用程序
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "learning_log.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "learning_log.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# 我的设置
LOGIN_URL = 'users:login'

# CloudBase 适配配置

# 1. 允许CloudBase域名访问（替代书中ALLOWED_HOSTS = []）
# 替换为你的域名

# 2. 静态文件配置（复用书中20.1.7的STATIC_ROOT，适配CloudBase静态托管）
STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')  # 书中已配置，无需修改
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'staticfiles')]  # 补充静态文件源目录

# 3. 数据库配置（兼容CloudBase云数据库，替换为MySQL逻辑）
DATABASES = {
    'default': {
        'ENGINE': os.getenv('DB_ENGINE', 'django.db.backends.mysql'),
        'NAME': os.getenv('DB_NAME', 'qinzheng123-8guhm42j495d526f'),  # 加默认值
        'USER': os.getenv('DB_USER', 'qinzheng'),
        'PASSWORD': os.getenv('DB_PASSWORD', 'Qz12345678'),
        'HOST': os.getenv('DB_HOST', 'sh-cynosdbmysql-grp-1vls57i0.sql.tencentcdb.com'),
        'PORT': os.getenv('DB_PORT', '23552'),
        'OPTIONS': {
            'charset': 'utf8mb4',
            'connect_timeout': 10,
            'ssl': {'verify_mode': 'NONE'}
        },
    }
}

# 4. DEBUG模式控制（复用书中20.2.12的环境变量逻辑，避免泄露调试信息）
# DEBUG = os.getenv('DEBUG', 'False') == 'True'  # 本地默认True，CloudBase部署设为False
